### ISSUE TITLE
nixd/documentLink: helix failed to parse: invalid type: boolean `true`, expected struct DocumentLinkOptions

### ISSUE THREAD

**Issue by happysalada** [nix-community/nixd#187]
Trying to use this with the helix editor, here is what I get when trying to run on a nix file.

```
2023-06-30T10:50:54.898 helix_lsp::transport [ERROR] nixd err <- "I[10:50:54.897] 9311: nixd 1.1.0 started\n"
2023-06-30T10:50:54.899 helix_lsp::transport [ERROR] nixd err <- "I[10:50:54.899] 9311: <-- initialize(0)\n"
2023-06-30T10:50:54.900 helix_lsp::transport [ERROR] nixd err <- "I[10:50:54.899] 9311: --> reply:initialize(0)\n"
2023-06-30T10:50:54.903 helix_lsp [ERROR] failed to initialize language server: failed to parse: invalid type: boolean `true`, expected struct DocumentLinkOptions
```

not sure if the issue is on helix side or on nixd, just opening this for discussion.

**Comment by inclyc** [comment]
Looks like it is a conformance bug in nixd:

https://github.com/nix-community/nixd/blob/c4557ca1c7955a08ed1cfc80f1edb844c582fc2b/nixd/tools/nixd/test/initialize.md?plain=1#L38

But the LSP specification said:

```
Server Capability:

property name (optional): documentLinkProvider
property type: [DocumentLinkOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentLinkOptions) defined as follows:
```

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

However, on vscode it is permissive and do not report any bug to me, and documentLink works fine, I would like to fix this in nixd for editors compatibility.

This issue is easy to fix, if you would like to contribute, please comment here :)

https://github.com/nix-community/nixd/blob/c4557ca1c7955a08ed1cfc80f1edb844c582fc2b/nixd/lib/Server/Controller.cpp#L277

Maybe just change this into:

```diff
- {"documentLinkProvider", true},
+ {"documentLinkProvider", llvm::json::Object{{"resolveProvider", false}}},
```

**Comment by happysalada** [comment]
Hey thanks for responding so quickly ! Im happy for you to make the change , but thanks for proposing me to contribute.
