### ISSUE TITLE
allow templating of hostname, fqdn and username for `options.target.installable`

### ISSUE THREAD

**Issue by wucke13** [nix-community/nixd#213]
Currently I have `".#homeConfigurations.wucke13@<hostname>.options"` as installable for my home-manager `.nixd.json` and `".#nixosConfigurations.<hostname>.options"` for my NixOS configuration. I would guess this is the case for most if not all users.
It would be cool, If these variables where available as template in the `.nixd.json` config, so that I could write `".#nixosConfigurations.${HOSTNAME}.options"` instead.

On an additional note: maybe there could be an lsp popup that could show the relevant items from `nix flake show --json` as installables for quick pick of what context is used for options completion on the fly.

Last but not least: allow for a nix expression that defines the available target installables. I.e. for my nixos configuration, the selection of valid installables for the popup would be:

````sh
nix eval '.#nixosConfigurations' --apply 'attrs: builtins.map (x: ".#nixosConfigurations.${x}.options") (builtins.attrNames attrs)' --json
````

**Comment by inclyc** [comment]
> It would be cool, If these variables where available as template in the .nixd.json config, so that I could write ".#nixosConfigurations.${HOSTNAME}.options" instead.

Agree that it is a good idea to provide such variables, because nix users usually defines `<hostname>` in some part of the attrpath. It may somehow tricky to be implemented, though, or we should provided a general interface to make the configuration more flexible.

 > On an additional note: maybe there could be an lsp popup that could show the relevant items from nix flake show --json as installables for quick pick of what context is used for options completion on the fly.

This might be implemented via LSP commands.

> allow for a nix expression that defines the available target installables

Nix expression can actually do any computations, and can be infinitely recursive. So maybe it is not a good idea to allow nix expressions as a configuration language. The evaluation requires IPC with the main controller process, and we do not know whether or not it can be terminated.

**Comment by inclyc** [comment]
In #415 we have "multiple" resources option support.

**Comment by musjj** [comment]
So how do we achieve this now? The issue was closed, but I don't see how the linked PR is relevant. Is there an example?
