### ISSUE TITLE
--version gives llvm version, not nixd version

### ISSUE THREAD

**Issue by bburdette** [nix-community/nixd#233]
```
[bburdette@HOSS:~/.config/helix]$ nixd --version
LLVM (http://llvm.org/):
  LLVM version 16.0.6
  Optimized build.
```

**Comment by inclyc** [comment]
lsp servers are not launched by CLIs, so I left the LLVM version string here. For other CLI tools, the version string is correct (e.g. nixd-ast-dump). This might be confusing for users.

**Comment by inclyc** [comment]
This issue is easy to fix, would you like to make contribution?

https://github.com/nix-community/nixd/blob/00d67dc7950146d08bbffe1f55d742f382341217/nixd/tools/nixd-ast-dump/nixd-ast-dump.cpp#L90-L98

Write similar stuff here:

https://github.com/nix-community/nixd/blob/00d67dc7950146d08bbffe1f55d742f382341217/nixd/tools/nixd/nixd.cpp#L123

**Comment by AkechiShiro** [comment]
@bburdette would you still like to do this fix or can I give it a try ?

**Comment by bburdette** [comment]
@AkechiShiro please do!
