### ISSUE TITLE
feature: switchable targets

### ISSUE THREAD

**Issue by poelzi** [nix-community/nixd#272]
The current target configuration is quite limiting in multi target environments.
It would be more flexible if the config would also contain a list of targets which are selectable with a code action.

```json
{
  "eval": {
      "targets": {
       "default": {
            "args": [
                "-f",
                "default.nix"
            ],
            "installable": ""
       },
       "my_pkg": {
            "args": [
                "-f",
                "default.nix"
            ],
            "installable": "foo"
      }
    }
  }
}
```

**Comment by inclyc** [comment]
> The current target configuration is quite limiting in multi target environments.

Yes, I admit this is limiting for such environments, for example users may want home-manager options hint when editing HM-files, and nixos options for nixos modules.

> It would be more flexible if the config would also contain a list of targets which are selectable with a code action.

https://github.com/nix-community/nixd/issues/213 gives me another solution, for example just provide templates for configuration.

> selectable with a code action

I workaround this by just comment parts of the configuration, since vscode support "JSON with comments" but this is not applicable for vim/emacs users.

I hope that there are some mechanics to track where options came from, so that we can provide completion lists automatically instead of configuring every workspace. However there is no such thing.

**Comment by inclyc** [comment]
"Eval" section has been deleted. And for options section, now you can write arbitrary nix expression (Turing complete) in your configuration, thus I think this should be closed? (Feel free to reopen also)
