### ISSUE TITLE
libnixf/Sema: a little pedantic if the fn arg is not used

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#463]
It is commonly used in real world that this pattern is used in overlays:

```nix
final: prev: ...
```

and likely the arguments will not be used. Currently there is no better renaming stuff for these unused argument (prefixes them with `_` basically looks ungly!).

**Comment by Atemu** [comment]
I was about to open an issue on this but you've already gone ahead and fixed it...

Another possibility would be to require `_` as names for the lambda args. This pattern is quite typical in Haskell and therefore also often used in Nix.

```Nix
mapAttrs (name: _: "actually only need the ${name}") attrs
```


```Nix
_: prev: ...
```

Not ideal but clearly marks those args as unused and does not look very ugly IMHO (`_somearg: ` certainly would though).

(If this approach were to be chosen, it should also be accommodated by an inverse check: that `_` is not actually used anywhere.)

Sometimes I find myself wanting to have common lambdas like `final: prev:` or `name: value:` eventhough one of the parameters is unused in order to ease pattern recognition though, so perhaps allowing this for any lambda arg is the better solution.
