### ISSUE TITLE
Variable gets declared as unused when used in path interpolation

### ISSUE THREAD

**Issue by Libadoxon** [nix-community/nixd#472]
![image](https://github.com/nix-community/nixd/assets/90480641/3c351b4a-f1c3-4bdf-8242-d900e1baabdd)

**Comment by inclyc** [comment]
This issue is easy to fix. Let's leave this to new contributors.


Modify this line:

https://github.com/nix-community/nixd/blob/b3515c91a56b9a1008a375116da46e9f8c8eb261/libnixf/include/nixf/Basic/Nodes/Simple.h#L157


To this:

https://github.com/nix-community/nixd/blob/b3515c91a56b9a1008a375116da46e9f8c8eb261/libnixf/include/nixf/Basic/Nodes/Simple.h#L140

**Comment by inclyc** [comment]
I'll take this.
